### ISSUE TITLE
Cannot clone repository on Windows 10

### ISSUE THREAD

**Issue by JarneRenders** [IMAGINARY/reinforcement-learning-2#2]
Cloning the repository on Windows 10 gives the error:

> error: invalid path 'src/js/aux/array-2d.js'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

The reason is because `aux` is reserved for legacy reasons on Windows:

> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces. 

See [here](https://msdn.microsoft.com/en-us/library/aa365247.aspx).

**Comment by elondaits** [comment]
😑 Oh, sorry! I'm old enough that I should have caught this, although I've been away from Windows for over a decade now.

I'm about to deploy a significant update with new functionality (should be out tomorrow, Monday) so I'll include this fix.

**Comment by elondaits** [comment]
I just released v1.2.0 which implements many updates and includes this issue.
